### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jesse-mm** [jesse-mm/sassify-webpack-plugin#1]
- [x] Update Readme
- [x] Create template vars
- [x] Publish to NPM
- [x] Implementation test (vue-skeleton)
- [x] Clean-up AbstractParser
- [x] Add build script for generating distribution
- [x] Prepare for npm publish
- [x] Write docs
- [x] Write tests!
- [x] Ditch moment, just check modification date has changed.
- [x] Use pify in combination with async/await
- [x] Create parse modules that can handle SingleExport, MultiExport (TS/JS)
- [x] Parse modules can have options
- [x] Update directory structure
- [x] Rename in/out to source/dest.
- [x] Create test environment
- [x] Check if we can swap out eval and use node child process to process a file
- [x] Rewrite source to TS
- [x] Add template files for generation output
- [x] Use [vm2](https://github.com/patriksimek/vm2) for executing code
- [x] Allow numeric values to be set in imported object.
- [x] Set unquoted sass-maps as default
- [x] Use path for getting filename or extension.
